### PR TITLE
Add 'addplaylist' and 'delplaylist' commands

### PR DESCRIPTION
**Pull request by ericyape**
Hi,
I would like to share 2 new mpc commands:
- `addplaylist <playlist> <file>`: add a file to a playlist
- `delplaylist <playlist> <position>`: remove the song at position from the playlist

NB : these 2 commands are using a new 'pipe' format descriptor (3) to allow the `<playlist>` argument to be added to the stdin arguments when used in a pipe statement...

Thanks in advance for any comment!
Eric

### CODE REVIEW

**Comment by ericyape** [comment]
Hi,
Just added the `moveplaylist <playlist> <from> <to>` command.
Eric

**Comment by ericyape** [comment]
Added one more playlist command : 
- `renplaylist <file> <newfile>` to rename a playlist

Eric

**Comment by ericyape** [comment]
Add one more playlist command :
- `clearplaylist <playlist>` to clear/truncate a playlist

Eric

**Comment by ericyape** [comment]
Hi Max @MaxKellermann ,
could you please take another look at the proposed PR ?
Thanks in advance for any help !
Eric

**Comment by jcorporation** [comment]
I merged this in my mpc fork that will be integrated in the next myMPDos version.

**Comment by MaxKellermann** [comment]
@ericyape sorry for the super-long delay. I've been extremely occupied all year.

**Comment by ericyape** [comment]
Hi @MaxKellermann 

Many thanks for merging the PR !

Do you think that it would be relevant to add a link to my music player project (https://gitlab.com/eric.yape/retrotube) on the MPD "Clients" page ?

Thanks for your time and your stunning projects.
Eric

**Comment by MaxKellermann** [comment]
This would be the right place to advertise MPD clients, so yes.

**Pull request merged**
