### PR TITLE
Add support for consume: oneshot

### PR DESCRIPTION
**Pull request by Mstrodl**
I think I got all the spots, but let me know if I missed anything!

### CODE REVIEW

**Comment by MaxKellermann** [comment]
This fails to build if you compile with libmpdclient 2.20 or older - mpc should be compatible with older libmpdclient releases (at least 2.18 as documented and specified in meson.build), and thus you need a compile-time check.

**Comment by Mstrodl** [comment]
Hey, I added version checks consistent with these old ones: https://github.com/MusicPlayerDaemon/mpc/commit/3ec52051b465c8392f6f264a215d03a309d0665b

**Comment by MaxKellermann** [comment]
The second commit just fixes mistakes in the first commit - this shouldn't be a separate commit, because it is not a separate work. The second commit even re-adds code that the first code deletes, which is confusing for review. Please amend existing commits if you find mistakes instead of adding fixup commits to the same unmerged PR.

**Comment by Mstrodl** [comment]
I squashed the commits, let me know if you have any other feedback.

**Pull request merged**
